services:
  postgres:
    image: postgres:16-alpine
    container_name: ewallet_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ewallet_data:/var/lib/postgresql/data

volumes:
  ewallet_data: